version: '2'
services:
    easymargining-app:
        image: easymargining
        external_links:
            - easymargining-mongodb:mongodb
            # Uncomment to have Cassandra working with the gateway
            # - easymargining-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=EasyMargining
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    easymargining-mongodb:
        extends:
            file: mongodb.yml
            service: easymargining-mongodb
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: easymargining-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
